[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/oca-addons/web,/mnt/oca-addons/account-financial-reporting,/mnt/oca-addons/mis-builder,/mnt/oca-addons/reporting-engine,/mnt/oca-addons/server-tools,/mnt/oca-addons/project,/mnt/oca-addons/knowledge,/mnt/oca-addons/hr,/mnt/oca-addons/server-ux,/mnt/oca-addons/calendar,/mnt/oca-addons/dms
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$BeD8X6v1nlNKae19L2WM0Q$PdXc4ikjHGZcOMG4r9iRmidTXDI/phk6H/Yo9urm.Ph8GWFB5qZyALUud8SszRWaSMqMn6S123J9VbInV4CnyA

